In [6]:
import numpy
import json
from pathlib import Path
from importlib import reload
import sys
import os
sys.path.append(os.path.abspath('..'))
import pandas as pd
import random
from transformers import AutoModel, AutoTokenizer
from utils.SemrepOutputLoader import SemrepOutputLoader
from utils.TermEmbedder import TermEmbedder
from HGCR_util.lazy_json_kv_loader import LazyJsonlAbstractLoader
from sklearn.model_selection import train_test_split
from HGCR_util import text_util
from HGCR_util.emb_lookup.abstr_emb_lookup import MedlineNumpyEmbeddings
from tqdm import tqdm
random.seed(42)

tqdm.pandas()

In [2]:
import importlib
import utils

importlib.reload(utils.TermEmbedder)

In [2]:
embeddings_fpath = Path(
    '/work/acslab/shared/medline_embeddings/PubMedNCL_abstr/abstr_id_to_emb_PubMedNCL'
)

pubmedncl_emb_obj = MedlineNumpyEmbeddings(
    emb_w_ids_fpath=embeddings_fpath,
    json_read_n_jobs=8,
)

Opening np chunks: 100%|██████████████████████| 102/102 [00:02<00:00, 39.72it/s]
Opening json index chunks: 100%|██████████████| 102/102 [00:12<00:00,  8.23it/s]
Constructing PMID lookup index: 100%|█████████| 102/102 [00:13<00:00,  7.64it/s]

In [9]:
folder_path = '/work/acslab/shared/rel_extraction/semrep_data/data_2021_onw/agatha_medline_sentences'
pkl_files = [f for f in os.listdir(folder_path) if f.endswith('.pkl')]

In [5]:
def attach_abstract_embeddings(data_dict, embedding_lookup):
    pmids_to_delete = []
    for pmid, entry in data_dict.items():
        if pmid in embedding_lookup:
            entry['abstract_embedding'] = embedding_lookup[pmid]
        else:
            pmids_to_delete.append(pmid)

    for pmid in pmids_to_delete:
        del data_dict[pmid]

    return data_dict

In [17]:
terms = set()
term_embedder = TermEmbedder()

i=0 

for file in tqdm(pkl_files):
    sr_output_dict = SemrepOutputLoader('/work/acslab/shared/rel_extraction/semrep_data/data_2021_onw/agatha_medline_sentences')
    sr_output_dict._load_single_pkl_file(file)

    data_dict = attach_abstract_embeddings(sr_output_dict.data_dict, pubmedncl_emb_obj)

    all_terms_set = set()
    relation_terms_set = set()

    for entry in data_dict.values():
        for sentence_terms in entry['terms']:
            for term, _ in sentence_terms:
                all_terms_set.add(term)
        for relation_list in entry['relations'] + entry['negatives']:
            for term1, term2 in relation_list:
                relation_terms_set.update([term1, term2])
    combined_terms = all_terms_set.union(relation_terms_set)
    terms.update(combined_terms)
    
    pmids = [pmid for pmid in list(data_dict.keys())]

    df = pd.DataFrame({
        'pmid': [pmid for pmid in pmids],
        'abstract': [data_dict[pmid].get('abstract_text') for pmid in pmids],
        'abstract_embeddings': [data_dict[pmid].get('abstract_embedding') for pmid in pmids],
        'terms': [data_dict[pmid].get('terms') for pmid in pmids],
        'relations': [data_dict[pmid].get('relations') for pmid in pmids],
        'negatives': [data_dict[pmid].get('negatives') for pmid in pmids],
    })

    chunk_size = 30000
    output_dir = '60k_pmid_dataset_chunks_sentencewise_negatives'
    
    for j, start in enumerate(range(0, len(df), chunk_size)):
        df_chunk = df.iloc[start:start+chunk_size]
        chunk_path = os.path.join(output_dir, f"chunk_{i}_{j}.pkl")
        df_chunk.to_pickle(chunk_path)
        print(f"Saved {chunk_path}")
    i+=1

  1%|▍                                        | 1/106 [00:57<1:40:32, 57.45s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_1_0.pkl

  2%|▊                                        | 2/106 [01:50<1:34:38, 54.60s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_1_1.pkl

  3%|█▏                                       | 3/106 [02:36<1:27:36, 51.03s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_2_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_3_0.pkl

  4%|█▌                                       | 4/106 [03:58<1:47:08, 63.02s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_3_1.pkl

  5%|█▉                                       | 5/106 [05:01<1:46:14, 63.11s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_4_0.pkl

  7%|██▋                                      | 7/106 [05:50<1:06:25, 40.26s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_7_0.pkl

  8%|███                                      | 8/106 [06:56<1:19:19, 48.56s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_7_1.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_8_0.pkl

  8%|███▍                                     | 9/106 [08:06<1:29:02, 55.07s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_8_1.pkl

  9%|███▊                                    | 10/106 [08:59<1:27:10, 54.49s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_9_0.pkl

 10%|████▏                                   | 11/106 [09:48<1:23:21, 52.65s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_11_0.pkl

 11%|████▌                                   | 12/106 [10:51<1:27:44, 56.00s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_11_1.pkl

 12%|████▉                                   | 13/106 [11:17<1:12:33, 46.81s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_12_0.pkl

 13%|█████▎                                  | 14/106 [12:05<1:12:16, 47.13s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_14_0.pkl

 14%|█████▋                                  | 15/106 [13:21<1:24:40, 55.83s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_14_1.pkl

 15%|██████                                  | 16/106 [14:14<1:22:41, 55.13s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_16_0.pkl

 16%|██████▍                                 | 17/106 [15:33<1:32:19, 62.25s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_16_1.pkl

 17%|██████▊                                 | 18/106 [16:23<1:25:45, 58.47s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_18_0.pkl

 18%|███████▏                                | 19/106 [17:36<1:31:22, 63.01s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_18_1.pkl

 19%|███████▌                                | 20/106 [18:33<1:27:46, 61.24s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_19_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_20_0.pkl

 20%|███████▉                                | 21/106 [19:19<1:19:59, 56.47s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_20_1.pkl

 21%|████████▎                               | 22/106 [19:46<1:06:52, 47.77s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_21_0.pkl

 22%|████████▋                               | 23/106 [20:35<1:06:31, 48.09s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_22_0.pkl

 23%|█████████                               | 24/106 [21:24<1:06:03, 48.34s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_23_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_24_0.pkl

 24%|█████████▍                              | 25/106 [22:31<1:12:49, 53.94s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_24_1.pkl

 25%|█████████▊                              | 26/106 [23:21<1:10:31, 52.89s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_26_0.pkl

 25%|██████████▏                             | 27/106 [24:34<1:17:14, 58.67s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_26_1.pkl

 28%|███████████▉                              | 30/106 [26:38<57:58, 45.76s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_29_0.pkl

 30%|████████████▋                             | 32/106 [28:18<59:11, 48.00s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_32_0.pkl

 31%|████████████▍                           | 33/106 [29:31<1:07:17, 55.31s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_32_1.pkl

 32%|████████████▊                           | 34/106 [30:19<1:03:54, 53.25s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_33_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_34_0.pkl

 33%|█████████████▏                          | 35/106 [31:28<1:08:29, 57.88s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_34_1.pkl

 36%|███████████████                           | 38/106 [33:58<59:19, 52.35s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_38_0.pkl

 37%|██████████████▋                         | 39/106 [35:05<1:03:10, 56.58s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_38_1.pkl

 38%|███████████████                         | 40/106 [36:04<1:03:18, 57.56s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_39_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_40_0.pkl

 39%|███████████████▍                        | 41/106 [37:01<1:02:06, 57.33s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_40_1.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_41_0.pkl

 40%|███████████████▊                        | 42/106 [38:13<1:05:39, 61.55s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_41_1.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_42_0.pkl

 41%|████████████████▏                       | 43/106 [39:26<1:08:22, 65.12s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_42_1.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_43_0.pkl

 42%|████████████████▌                       | 44/106 [40:11<1:00:58, 59.01s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_43_1.pkl

 42%|█████████████████▊                        | 45/106 [40:57<56:03, 55.13s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_45_0.pkl

 43%|██████████████████▏                       | 46/106 [41:56<56:13, 56.22s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_45_1.pkl

 44%|██████████████████▌                       | 47/106 [42:50<54:38, 55.57s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_46_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_47_0.pkl

 45%|███████████████████                       | 48/106 [43:58<57:19, 59.29s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_47_1.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_48_0.pkl

 46%|███████████████████▍                      | 49/106 [45:07<59:11, 62.31s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_48_1.pkl

 47%|███████████████████▊                      | 50/106 [45:50<52:47, 56.56s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_50_0.pkl

 48%|████████████████████▏                     | 51/106 [46:59<55:10, 60.19s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_50_1.pkl

 49%|████████████████████▌                     | 52/106 [47:45<50:27, 56.06s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_51_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_52_0.pkl

 50%|█████████████████████                     | 53/106 [48:53<52:42, 59.67s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_52_1.pkl

 51%|█████████████████████▍                    | 54/106 [49:45<49:44, 57.40s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_53_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_54_0.pkl

 52%|█████████████████████▊                    | 55/106 [50:38<47:39, 56.08s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_54_1.pkl

 53%|██████████████████████▏                   | 56/106 [51:24<44:09, 52.99s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_56_0.pkl

 54%|██████████████████████▌                   | 57/106 [52:12<41:54, 51.32s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_56_1.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_57_0.pkl

 55%|██████████████████████▉                   | 58/106 [53:28<47:05, 58.87s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_57_1.pkl

 56%|███████████████████████▍                  | 59/106 [54:15<43:11, 55.15s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_59_0.pkl

 57%|███████████████████████▊                  | 60/106 [55:24<45:32, 59.40s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_59_1.pkl

 58%|████████████████████████▏                 | 61/106 [56:15<42:44, 56.99s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_61_0.pkl

 58%|████████████████████████▌                 | 62/106 [57:21<43:36, 59.48s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_61_1.pkl

 59%|████████████████████████▉                 | 63/106 [58:18<42:13, 58.92s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_63_0.pkl

 60%|█████████████████████████▎                | 64/106 [59:11<39:59, 57.12s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_63_1.pkl

 61%|████████████████████████▌               | 65/106 [1:00:01<37:34, 54.99s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_64_0.pkl

 62%|████████████████████████▉               | 66/106 [1:00:11<27:34, 41.37s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_65_0.pkl

 63%|█████████████████████████▎              | 67/106 [1:00:33<23:07, 35.57s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_66_0.pkl

 65%|██████████████████████████              | 69/106 [1:02:14<26:37, 43.18s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_69_0.pkl

 66%|██████████████████████████▍             | 70/106 [1:03:28<31:26, 52.40s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_69_1.pkl

 67%|██████████████████████████▊             | 71/106 [1:04:13<29:14, 50.12s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_71_0.pkl

 68%|███████████████████████████▏            | 72/106 [1:05:25<32:05, 56.62s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_71_1.pkl

 69%|███████████████████████████▌            | 73/106 [1:06:19<30:41, 55.81s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_72_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_73_0.pkl

 70%|███████████████████████████▉            | 74/106 [1:07:19<30:27, 57.12s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_73_1.pkl

 71%|████████████████████████████▎           | 75/106 [1:08:10<28:29, 55.16s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_75_0.pkl

 72%|████████████████████████████▋           | 76/106 [1:09:23<30:15, 60.51s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_75_1.pkl

 73%|█████████████████████████████           | 77/106 [1:10:08<27:03, 55.97s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_77_0.pkl

 74%|█████████████████████████████▍          | 78/106 [1:11:07<26:31, 56.85s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_77_1.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_78_0.pkl

 75%|█████████████████████████████▊          | 79/106 [1:12:08<26:08, 58.11s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_78_1.pkl

 75%|██████████████████████████████▏         | 80/106 [1:12:50<23:02, 53.18s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_79_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_80_0.pkl

 76%|██████████████████████████████▌         | 81/106 [1:13:57<23:54, 57.38s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_80_1.pkl

 78%|███████████████████████████████▎        | 83/106 [1:15:33<20:10, 52.61s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_82_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_83_0.pkl

 79%|███████████████████████████████▋        | 84/106 [1:16:28<19:33, 53.33s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_83_1.pkl

 80%|████████████████████████████████        | 85/106 [1:16:51<15:31, 44.37s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_84_0.pkl

 83%|█████████████████████████████████▏      | 88/106 [1:18:49<11:30, 38.36s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_87_0.pkl

 84%|█████████████████████████████████▌      | 89/106 [1:19:38<11:48, 41.65s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_89_0.pkl

 85%|█████████████████████████████████▉      | 90/106 [1:20:40<12:45, 47.84s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_89_1.pkl

 86%|██████████████████████████████████▎     | 91/106 [1:21:39<12:48, 51.26s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_91_0.pkl

 87%|██████████████████████████████████▋     | 92/106 [1:22:30<11:55, 51.12s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_91_1.pkl

 89%|███████████████████████████████████▍    | 94/106 [1:24:18<10:31, 52.61s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_93_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_94_0.pkl

 90%|███████████████████████████████████▊    | 95/106 [1:25:17<09:57, 54.36s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_94_1.pkl

 91%|████████████████████████████████████▏   | 96/106 [1:26:07<08:51, 53.14s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_96_0.pkl

 92%|████████████████████████████████████▌   | 97/106 [1:27:06<08:15, 55.02s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_96_1.pkl

 92%|████████████████████████████████████▉   | 98/106 [1:27:57<07:08, 53.60s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_98_0.pkl

 93%|█████████████████████████████████████▎  | 99/106 [1:28:49<06:13, 53.34s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_98_1.pkl

 96%|█████████████████████████████████████▌ | 102/106 [1:31:01<03:07, 46.88s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_101_0.pkl
Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_102_0.pkl

 97%|█████████████████████████████████████▉ | 103/106 [1:31:52<02:24, 48.30s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_102_1.pkl

 98%|██████████████████████████████████████▎| 104/106 [1:32:36<01:34, 47.05s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_104_0.pkl

 99%|██████████████████████████████████████▋| 105/106 [1:33:13<00:44, 44.06s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_104_1.pkl

100%|███████████████████████████████████████| 106/106 [1:34:06<00:00, 53.27s/it]

Saved 60k_pmid_dataset_chunks_sentencewise_negatives/chunk_105_0.pkl

In [4]:
import pickle
with open('all_terms.pkl', 'rb') as file:
    terms = pickle.load(file)
len(terms)

2894344

In [5]:
t = TermEmbedder(batch_size=1024)

In [6]:
embed_dict = t._batch_term_embeds(list(terms))

In [7]:
with open('embed_dict.pkl', 'wb') as file:
    pickle.dump(embed_dict, file)

In [6]:
list(os.listdir(chunk_dir))[0]

'chunk_34_0.pkl'

In [7]:
def extract_all_semantic_types(chunk_dir):
    import pickle
    import os
    import tqdm

    all_sem_types = set()

    for fname in tqdm.tqdm(os.listdir(chunk_dir), desc="Scanning all semantic types"):
        if not fname.endswith('pkl'):
            continue
            
        df = pd.read_pickle(os.path.join(chunk_dir, fname))
        for idx, row in df.iterrows():
            terms_list = row['terms']
            for sentence_terms in terms_list:
                for _, sem_types in sentence_terms:
                    all_sem_types.update(sem_types)

    sorted_types = sorted(all_sem_types)
    sem_types_to_idx = {stype: i for i, stype in enumerate(sorted_types)}

    return sem_types_to_idx

In [8]:
chunk_dir = '60k_pmid_dataset_chunks_sentencewise_negatives'

sem_types = extract_all_semantic_types(chunk_dir)

Scanning all semantic types: 100%|████████████| 116/116 [40:23<00:00, 20.89s/it]

In [5]:
sem_types

{'': 0,
 'aapp': 1,
 'acab': 2,
 'acty': 3,
 'aggp': 4,
 'amas': 5,
 'amph': 6,
 'anab': 7,
 'anim': 8,
 'anst': 9,
 'antb': 10,
 'arch': 11,
 'bacs': 12,
 'bact': 13,
 'bdsu': 14,
 'bdsy': 15,
 'bhvr': 16,
 'biof': 17,
 'bird': 18,
 'blor': 19,
 'bmod': 20,
 'bodm': 21,
 'bpoc': 22,
 'bsoj': 23,
 'celc': 24,
 'celf': 25,
 'cell': 26,
 'cgab': 27,
 'chem': 28,
 'chvf': 29,
 'chvs': 30,
 'clas': 31,
 'clna': 32,
 'clnd': 33,
 'cnce': 34,
 'comd': 35,
 'crbs': 36,
 'diap': 37,
 'dora': 38,
 'drdd': 39,
 'dsyn': 40,
 'edac': 41,
 'eehu': 42,
 'elii': 43,
 'emod': 44,
 'emst': 45,
 'enty': 46,
 'enzy': 47,
 'evnt': 48,
 'famg': 49,
 'ffas': 50,
 'fish': 51,
 'fndg': 52,
 'fngs': 53,
 'food': 54,
 'ftcn': 55,
 'genf': 56,
 'geoa': 57,
 'gngm': 58,
 'gora': 59,
 'grpa': 60,
 'grup': 61,
 'hcpp': 62,
 'hcro': 63,
 'hlca': 64,
 'hops': 65,
 'horm': 66,
 'humn': 67,
 'idcn': 68,
 'imft': 69,
 'inbe': 70,
 'inch': 71,
 'inpo': 72,
 'inpr': 73,
 'irda': 74,
 'lang': 75,
 'lbpr': 76,
 'lbtr': 77,
 'mamm': 78,
 'mbrt': 79,
 'mcha': 80,
 'medd': 81,
 'menp': 82,
 'mnob': 83,
 'mobd': 84,
 'moft': 85,
 'mosq': 86,
 'neop': 87,
 'nnon': 88,
 'npop': 89,
 'nusq': 90,
 'ocac': 91,
 'ocdi': 92,
 'orch': 93,
 'orga': 94,
 'orgf': 95,
 'orgm': 96,
 'orgt': 97,
 'ortf': 98,
 'patf': 99,
 'phob': 100,
 'phpr': 101,
 'phsf': 102,
 'phsu': 103,
 'plnt': 104,
 'podg': 105,
 'popg': 106,
 'prog': 107,
 'pros': 108,
 'qlco': 109,
 'qnco': 110,
 'rcpt': 111,
 'rept': 112,
 'resa': 113,
 'resd': 114,
 'rnlw': 115,
 'sbst': 116,
 'shro': 117,
 'socb': 118,
 'sosy': 119,
 'spco': 120,
 'tisu': 121,
 'tmco': 122,
 'topp': 123,
 'virs': 124,
 'vita': 125,
 'vtbt': 126}

In [4]:
df = pd.read_pickle(os.path.join(chunk_dir, 'chunk_34_0.pkl'))
df.head()

,pmid,abstract,abstract_embeddings,terms,relations,negatives,terms_one_hot
0,36172010,Off on the Wrong Foot: Task Avoidance at the O...,"[-0.2419106, 0.14318974, -0.5393433, -0.743649...","[[(Wrong, ['qlco']), (Foot, ['bpoc']), (Task, ...","[[], [], [], [], [], [], [], [(difficulties, p...","[[(Academic, Avoidance), (Peer Acceptance, Pri...","[[(Wrong, [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0..."
1,36172011,Plant-based production and characterization of...,"[-0.048058104, -0.56592053, 0.3047429, -0.3238...","[[(Plant, ['plnt']), (based, ['ftcn']), (produ...","[[], [], [], [(Parathyroid Hormone, osteoporos...","[[(Plant, based), (characterization, induced),...","[[(Plant, [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0..."
2,36172012,Dual drug delivery platforms for bone tissue e...,"[-0.30017737, -0.5976623, -0.119359925, 0.3015...","[[(Dual, ['inpr']), (drug, ['phsu']), (deliver...","[[], [], [], [], []]","[[(Dual, drug), (Dual, delivery), (delivery, e...","[[(Dual, [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ..."
3,36172013,The effects of process parameters on polydopam...,"[-0.2239648, -0.8723455, -0.21922404, -0.09931...","[[(effects, ['qlco']), (process, ['phpr']), (p...","[[], [], [], [], []]","[[(effects, tissue engineering), (process, tis...","[[(effects, [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0..."
4,36172015,CSF circulation and dispersion yield rapid cle...,"[-0.29901206, -0.7229248, -0.0711912, -0.18861...","[[(CSF circulation, ['ortf']), (dispersion, ['...","[[], [(cerebrospinal fluid, choroid plexus)], ...","[[(CSF circulation, rapid), (dispersion, intra...","[[(CSF circulation, [0 0 0 0 0 0 0 0 0 0 0 0 0..."

In [5]:
df.iloc[0]['terms_one_hot']

[[('Wrong',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('Foot',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('Task',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('Avoidance',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('Primary School',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('Academic',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('Difficulties',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('Declining',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('Peer Acceptance',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))],
 [('present',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('study',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('academic',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('declining',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('peer',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('social status',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))],
 [('Participants',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('boys',
   array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('girls',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('students',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('ages',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))],
 [('year',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int32)),
  ('teachers',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('assessments',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('academic',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('task',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('avoidance',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('students',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('measures',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('math',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('achievement',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))],
 [('peer',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))],
 [('model',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('results',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('lack',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('interest',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('motivation',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('primary school',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('downward',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('academic',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('difficulties',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('diminished',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)),
  ('peer acceptance',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))],
 [('academic',
   array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [16]:
import numpy as np

def add_terms_one_hot_column(df, sem_type_to_idx):
    def encode_terms(terms_sentences):
        result = []
        for sentence in terms_sentences:
            encoded_sentence = []
            for term, sem_types in sentence:
                vec = np.zeros(len(sem_type_to_idx), dtype=np.int32)
                for st in sem_types:
                    idx = sem_type_to_idx.get(st)
                    if idx is not None:
                        vec[idx] = 1
                encoded_sentence.append((term, vec))
            result.append(encoded_sentence)
        return result
    df['terms_one_hot'] = df['terms'].apply(encode_terms)
    return df

In [17]:
new_df = add_terms_one_hot_column(df, sem_types)

In [24]:
for fname in tqdm(os.listdir(chunk_dir), desc="Scanning all semantic types"):
    if not fname.endswith('pkl'):
        continue

    temp_df = pd.read_pickle(os.path.join(chunk_dir, fname))
    temp_df = add_terms_one_hot_column(temp_df, sem_types)

    temp_df.to_pickle(os.path.join(chunk_dir, fname))

Scanning all semantic types: 100%|████████████| 116/116 [56:29<00:00, 29.22s/it]

In [23]:
df = pd.DataFrame({
    'pmid': [pmid for pmid in filtered_sampled_pmids],
    'abstract': [sampled_abstracts[pmid] for pmid in filtered_sampled_pmids],
    'abstract_embeddings': [sampled_embeds[pmid] for pmid in filtered_sampled_pmids],
    'terms': [
        [{'term': term, 'sem_types': sem_types} for term, sem_types in sr_output_dict[pmid][0]['terms'].items()]
    for pmid in filtered_sampled_pmids],
    'relations': [list(sr_output_dict[pmid][0]['relations']) for pmid in filtered_sampled_pmids],
    'negatives': [list(sr_output_dict[pmid][0]['negatives']) for pmid in filtered_sampled_pmids],

})

df.head()

,pmid,abstract,abstract_embeddings,terms,relations,negatives
0,34645169,[Comparative study on prognosis of neoadjuvant...,"[0.49783543, -0.36796388, 0.07800497, -0.39309...","[{'term': 'study', 'sem_types': {'resa'}}, {'t...","[(hepatic surgery, liver metastasis), (liver m...","[(hepatic surgery, synchronous), (colorectal, ..."
1,34645170,[Meta analysis of whether cytoreductive surger...,"[0.54596573, -0.5523745, 0.3862075, -0.3049447...","[{'term': 'Meta analysis', 'sem_types': {'resa...","[(hyperthermic intraperitoneal chemotherapy, s...","[(Meta analysis, hyperthermic intraperitoneal ..."
2,34645171,[Preliminary application and efficacy analysis...,"[0.46609217, -0.53439486, -0.30724216, -0.2693...","[{'term': 'Preliminary', 'sem_types': {'tmco'}...",[],"[(efficacy, transumbilical), (one, robotic), (..."
3,34645172,[Efficacy observation of the caudal-medial app...,"[-0.13429396, -0.28374758, -0.55942017, -0.131...","[{'term': 'Efficacy', 'sem_types': {'resa'}}, ...",[],"[(Efficacy, laparoscopic right hemicolectomy),..."
4,34645173,[Advances in researches on neoadjuvant therapy...,"[0.27427733, -0.30455527, 0.2711635, -0.158520...","[{'term': 'neoadjuvant therapy', 'sem_types': ...","[(liver metastasis, neoadjuvant therapy)]","[(colorectal, liver metastasis), (neoadjuvant ..."

In [24]:
def map_terms(row):
    terms = row['terms']
    embeds = []
    for term in terms:
        embeds.append(term_embeddings[term])
    return embeds

def map_pairs(row):
    pairs = row['relations']
    pair_embeds = []
    for t1, t2 in pairs:
        t1_embed = term_embeddings[t1]
        t2_embed = term_embeddings[t2]
        pair_embeds.append((t1_embed, t2_embed))
    return pair_embeds

def map_negatives(row):
    negatives = row['negatives']
    negative_embeds = []
    for t1, t2 in negatives:
        t1_embed = term_embeddings[t1]
        t2_embed = term_embeddings[t2]
        negative_embeds.append((t1_embed, t2_embed))
    return negative_embeds

100%|███████████████████████████████| 618054/618054 [00:03<00:00, 176492.94it/s]
100%|████████████████████████████████| 618054/618054 [00:08<00:00, 69848.54it/s]

,pmid,abstract,abstract_embeddings,terms,relations,negatives,pair_embeddings,negatives_embeddings
0,34645169,[Comparative study on prognosis of neoadjuvant...,"[0.49783543, -0.36796388, 0.07800497, -0.39309...","[{'term': 'study', 'sem_types': {'resa'}}, {'t...","[(hepatic surgery, liver metastasis), (liver m...","[(hepatic surgery, synchronous), (colorectal, ...","[([-0.18668774, 0.08872222, -0.6607132, -0.514...","[([-0.18668774, 0.08872222, -0.6607132, -0.514..."
1,34645170,[Meta analysis of whether cytoreductive surger...,"[0.54596573, -0.5523745, 0.3862075, -0.3049447...","[{'term': 'Meta analysis', 'sem_types': {'resa...","[(hyperthermic intraperitoneal chemotherapy, s...","[(Meta analysis, hyperthermic intraperitoneal ...","[([-0.85826594, 0.20347765, -0.9961403, -0.367...","[([-0.35334474, -0.029209832, -0.64358836, -0...."
2,34645171,[Preliminary application and efficacy analysis...,"[0.46609217, -0.53439486, -0.30724216, -0.2693...","[{'term': 'Preliminary', 'sem_types': {'tmco'}...",[],"[(efficacy, transumbilical), (one, robotic), (...",[],"[([-0.45889822, 0.25162315, -0.29522184, -0.10..."
3,34645172,[Efficacy observation of the caudal-medial app...,"[-0.13429396, -0.28374758, -0.55942017, -0.131...","[{'term': 'Efficacy', 'sem_types': {'resa'}}, ...",[],"[(Efficacy, laparoscopic right hemicolectomy),...",[],"[([-0.45889822, 0.25162315, -0.29522184, -0.10..."
4,34645173,[Advances in researches on neoadjuvant therapy...,"[0.27427733, -0.30455527, 0.2711635, -0.158520...","[{'term': 'neoadjuvant therapy', 'sem_types': ...","[(liver metastasis, neoadjuvant therapy)]","[(colorectal, liver metastasis), (neoadjuvant ...","[([-0.52805567, 0.24041682, -0.83669657, -0.39...","[([-0.50668895, 0.2471461, -0.66131216, -0.645..."

In [20]:
from itertools import combinations

def generate_negative_samples(row):
    terms = set(row['terms'])
    pairs = {tuple(sorted(pair)) for pair in row['relations']}

    all_possible_negatives = {tuple(sorted(pair)) for pair in combinations(terms, 2)}

    negative_pairs = list(all_possible_negatives - pairs)

    negative_pair_embeddings = [(term_embeddings[pair[0]], term_embeddings[pair[1]]) for pair in negative_pairs]

    return pd.Series([negative_pairs, negative_pair_embeddings])

df[['negative_pairs', 'negative_pair_embeddings']] = df.progress_apply(generate_negative_samples, axis=1)

100%|██████████████████████████████████| 194880/194880 [03:20<00:00, 972.42it/s]

In [21]:
pos = 0
neg = 0
for idx, row in df.iterrows():
    num_pos = len(row['relations'])
    num_neg = len(row['negative_pairs'])
    pos += num_pos
    neg += num_neg

neg/pos

84.99117967344438

In [22]:
df.head()

,pmid,abstract,abstract_embeddings,terms,relations,term_embeddings,pair_embeddings,negative_pairs,negative_pair_embeddings
0,33383987,Temperature and Solvent Effects on H2 Splittin...,"[-0.28345045, -0.54292804, 0.16380529, 0.15494...","[unique, dependence, increase, kinetic barrier...","[(kinetic barrier, individual), (tetrahydrofur...","[[-0.17409305, 0.14344533, -0.08849688, 0.0577...","[([-0.3733754, 0.3167213, -0.109789714, 0.1208...","[(catalytic activity, degrees C), (splitting, ...","[([-0.5648823, 0.017226646, -0.004290537, -0.3..."
1,33383988,Mechanism for Rapid Conversion of Amines to Am...,"[-0.2850943, -0.80024165, -0.11266672, 0.14250...","[SA, amines, heterogeneous, more, Born, scales...","[(Amines, Ammonium Salts), (methylamine, sulfu...","[[-0.2324654, 0.15819652, 0.13121484, -0.16349...","[([-0.34281886, 0.30733573, -0.13176091, 0.137...","[(Rapid, methylamine), (effect, sulfuric acid)...","[([-0.5999069, 0.08327565, -0.2641165, -0.0731..."
2,33383989,Bisecting GlcNAc Protein N-Glycosylation Is Ch...,"[-0.040046073, -1.0489765, -0.37665504, -0.493...","[structural, Protein N-Glycosylation, total, m...","[(adipose-derived stem cells, cell types), (gl...","[[-0.36078623, 0.14125407, -0.13912392, -0.101...","[([-0.54336065, -0.51505405, -0.42755878, 0.51...","[(PGC-LC, glycan), (protein N, three), (adipoc...","[([-0.79083776, -0.288387, -0.16368967, -0.216..."
3,33383992,Association of Exposure to Cattle with Self-Re...,"[-0.310526, -0.5039563, 0.6601208, -0.08117764...","[One Health, bovine tuberculosis, study, human...","[(health, human)]","[[-0.25943512, -0.07382132, -0.3403496, -0.090...","[([0.006518982, 0.25178033, -0.0104505485, -0....","[(health, study), (One Health, health), (bovin...","[([0.006518982, 0.25178033, -0.0104505485, -0...."
4,33383995,The Effect of Preoperative Video Based Pain Tr...,"[0.091471456, -0.07006314, -0.11821665, -0.306...","[preoperative, video, pain levels, operation, ...","[(Total Knee Arthroplasty, Patients), (total k...","[[-0.34140453, -0.05907702, -0.2574163, -0.370...","[([-0.8438509, 0.14522868, -0.4953759, -0.1401...",[(non-randomized control group intervention st...,"[([-0.49223354, -0.864952, -0.7692929, -0.1749..."

In [26]:
i=0

In [27]:
chunk_size = 30000
output_dir = '60k_pmid_dataset_chunks_sentencewise_negatives'
os.makedirs(output_dir, exist_ok=True)

for _, start in enumerate(range(0, len(df), chunk_size)):
    df_chunk = df.iloc[start:start+chunk_size]
    chunk_path = os.path.join(output_dir, f"chunk_{i}.pkl")
    df_chunk.to_pickle(chunk_path)
    print(f"Saved {chunk_path}")
    i+=1

KeyboardInterrupt:

In [61]:
len(df.iloc[0]['pair_embeddings'])

2

In [69]:
df.iloc[1000]['pair_embeddings'][0][0].shape

(768,)

In [70]:
df.head(1)

,pmid,abstract,abstract_embeddings,terms,relations,term_embeddings,pair_embeddings,negative_relations,negative_relation_embeddings
0,33439050,Radiohistologic Comparison Study of Temporal B...,"[0.1367508, -0.20444079, -0.7152996, -0.035280...","[specimen, data, inner, Cochlear Implant, coch...","[(spiral lamina, osseous), (bone structures, o...","[[-0.55541235, -0.023848163, -0.04390437, -0.0...","[([-0.3612353, -0.29702, 0.16018414, -0.321839...","[(Cone-Beam CT, implantation), (data, images),...","[([-0.7141436, -0.29975635, 0.07302878, -0.255..."